{% set name = 'h5r' %}
{% set version = 'v1.4.9' %}

package:
  name: r-{{ name }}
  version: {{ version|replace("-", "_") }}

source:
  svn_url: svn://svn.r-forge.r-project.org/svnroot/h5r/
  svn_rev: 97
  svn_ignore_externals: False # (defaults to False)

build:
  number: 0
  skip: False
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - r-base
    - hdf5
  run:
    - r-base
    - hdf5

test:
    commands:
      - '$R -e "library(''{{ name }}'')"'

about:
    home: http://r-forge.r-project.org/projects/h5r/
    license: LGPL
