{% set name = "clust" %}
{% set version = "1.10.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/c/clust/clust-{{ version }}.tar.gz
  sha256: db98bc778389ccf52a2ed00635fd944344f18d7c296f0d375ac0fa3111b2873d

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools
    - numpy
    - pandas
    - scipy
    - scikit-learn
    - matplotlib
    - portalocker
    - joblib
  run:
    - python
    - numpy
    - pandas
    - scipy
    - scikit-learn
    - matplotlib
    - portalocker
    - joblib

test:
  imports:
    - clust
  commands:
    - clust

about:
  home: https://github.com/baselabujamous/clust
  license: GNU Lesser General Public License v3.0
  summary: Optimised consensus clustering of multiple heterogeneous datasets.

extra:
  identifiers:
    - doi:10.1186/s13059-018-1536-8
