{% set name = "clust" %}
{% set version = "1.10.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/c/clust/clust-{{ version }}.tar.gz
  sha256: d82f0b6868e13ea8d050d1678e3a2d8741ec8e32cba14ed1b9f31bcee1d71e66

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python=3.7
    - pip
    - setuptools
    - matplotlib >=2.2*
  run:
    - python=3.7
    - numpy
    - pandas
    - scipy
    - scikit-learn
    - matplotlib >=2.2*
    - portalocker
    - joblib

test:
  imports:
    - clust
  commands:
    - clust

about:
  home: https://github.com/baselabujamous/clust
  license: University of Oxford Academic Use Licence
  summary: Optimised consensus clustering of multiple heterogeneous datasets.

extra:
  identifiers:
    - doi:10.1186/s13059-018-1536-8
