{% set name = "slivar" %}
{% set version = "0.0.6" %}
{% set sha256hash = "df315e1f03ee4baa3d67e16e4a0ed32065ad3a1187550460b5170f424c142d6e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brentp/slivar/releases/download/v{{ version }}/slivar_static
  sha256: {{ sha256hash }}

build:
  number: 0
  skip: True  # [osx]

requirements:
  build:
  host:
    - htslib
    - zlib
  run:
    - htslib
    - zlib

test:
  commands:
    - slivar 2>&1 | grep slivar

about:
  home: https://github.com/brentp/slivar
  license: MIT
  summary: 'filter/annotate variants in VCF/BCF format with simple expressions'
